gravity:
  gunicorn:
    bind: 0.0.0.0:8080
  celery:
  gx_it_proxy:
  tusd:
  reports:

galaxy:
  admin_users:
   - admin@hotmail.co.uk
   - test@testing.org
  builds_file_path: /galaxy/server/tool-data/shared/ucsc/builds.txt.sample
  container_resolvers_config_file: ''
  data_dir: /galaxy/server/database
  data_manager_config_file: /galaxy/server/config/data_manager_conf.xml.sample
  datatypes_config_file: /galaxy/server/config/datatypes_conf.xml
  dependency_resolvers_config_file: /galaxy/server/config/dependency_resolvers_conf.xml
  external_service_type_config_file: /galaxy/server/config/external_service_types_conf.xml.sample
  file_path: /galaxy/server/database/datasets
  integrated_tool_panel_config: /galaxy/server/config/integrated_tool_panel.xml
  job_metrics_config_file: /galaxy/server/config/job_metrics_conf.xml
  job_working_directory: /galaxy/server/database/jobs
  migrated_tools_config: /galaxy/server/config/migrated_tools_conf.xml
  openid_config_file: /galaxy/server/config/openid_conf.xml.sample
  shed_data_manager_config_file: /galaxy/server/config/shed_data_manager_conf.xml
  shed_tool_config_file: /galaxy/server/config/shed_tool_conf.xml
  shed_tool_data_table_config: /galaxy/server/config/shed_tool_data_table_conf.xml
  tool_config_file: /galaxy/server/config/tool_conf.xml.sample
  job_config_file: /galaxy/server/config/job_conf.xml
  tool_data_path: /galaxy/server/database/tool_data
  tool_data_table_config_path: /galaxy/server/config/tool_data_table_conf.xml.sample
  tool_dependency_dir: /galaxy/server/database/dependencies
  tool_sheds_config_file: /galaxy/server/config/tool_sheds_conf.xml.sample
  ucsc_build_sites: /galaxy/server/tool-data/shared/ucsc/ucsc_build_sites.txt.sample
  visualization_plugins_directory: config/plugins/visualizations
  cleanup_job: never
